import{a as b,S as L,i as c}from"./assets/vendor-Db2TdIkw.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function t(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(o){if(o.ep)return;o.ep=!0;const r=t(o);fetch(o.href,r)}})();async function f(e,s=1){return(await b.get("https://pixabay.com/api/",{params:{key:"49539312-1d6717d33bfa63c1c4ab44e48",q:`${e}`,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}})).data}const p=document.querySelector(".gallery");document.querySelector(".loader");const S=new L(".gallery a",{captionsData:"alt",captionDelay:250});function h(e){const s=e.map(t=>`
    <li class="gallery-item">
      <a href="${t.largeImageURL}" class="gallery-link">
        <img src="${t.webformatURL}" alt="${t.tags}" class="gallery-img"/>
        </a>
      <ul class="info-list">
        <li class="info-item"><span><b>Likes</b>${t.likes}</span></li>
        <li class="info-item"><span><b>Views</b>${t.views}</span></li>
        <li class="info-item"><span><b>Comments</b>${t.comments}</span></li>
        <li class="info-item"><span><b>Downloads</b>${t.downloads}</span></li>
      </ul>
    </li>
  `).join("");p.innerHTML=s,S.refresh()}function u(){const e=document.querySelector(".loader");e.style.display="block"}function m(){const e=document.querySelector(".loader");e.style.display="none"}function q(){p.innerHTML=""}function g(){const e=document.querySelector(".load-more-btn");e.style.display="block"}function y(){const e=document.querySelector(".load-more-btn");e.style.display="none"}const w=document.querySelector(".form");document.querySelector('[name="search-text"]');document.querySelector('[type="submit"]');document.querySelector(".gallery");let P="",a=1;const n=15;let d=0;y();m();w.addEventListener("submit",async e=>{e.preventDefault(),u();const s=e.target.elements[0].value.trim();if(!s){showAlert("Please enter a search term.");return}a=1,q(),y(),u();try{const t=await f(s,a,n);if(d=t.totalHits,t.hits.length===0){showAlert("Sorry, there are no images matching your search query. Please try again!");return}h(t.hits),n*a<d&&g()}catch(t){c.error({message:"Error loading images.",position:"topRight"}),console.error(t)}finally{m()}});const v=async()=>{a+=1,y(),u();try{const e=await f(P,a,n);h(e.hits),n*a<d?g():c.info({message:"We are sorry, but you`ve reached the search results.",position:"topRight"})}catch(e){c.error({message:"Failed to load more images.",position:"topRight"}),console.error(e)}finally{m()}};document.addEventListener("click",e=>{e.target.matches(".load-more-btn")&&v()});
//# sourceMappingURL=index.js.map
