import{a as w,S,i as n}from"./assets/vendor-Db2TdIkw.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&c(u)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();async function m(r,s=1){return(await w.get("https://pixabay.com/api/",{params:{key:"49539312-1d6717d33bfa63c1c4ab44e48",q:`${r}`,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}})).data}const y=document.querySelector(".gallery"),f=document.querySelector(".loader"),g=document.querySelector(".load-more-btn"),q=new S(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const s=r.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}" class="gallery-link">
        <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-img"/>
        </a>
      <ul class="info-list">
        <li class="info-item"><span><b>Likes</b>${e.likes}</span></li>
        <li class="info-item"><span><b>Views</b>${e.views}</span></li>
        <li class="info-item"><span><b>Comments</b>${e.comments}</span></li>
        <li class="info-item"><span><b>Downloads</b>${e.downloads}</span></li>
      </ul>
    </li>
  `).join("");y.insertAdjacentHTML("beforeend",s),q.refresh()}function b(){f.style.display="block"}function i(){f.style.display="none"}function P(){y.innerHTML=""}function L(){g.style.display="block"}function p(){g.style.display="none"}const R=document.querySelector(".form");document.querySelector('[name="search-text"]');document.querySelector('[type="submit"]');document.querySelector(".gallery");let v="",a=1;const l=15;let d=0;p();i();R.addEventListener("submit",async r=>{r.preventDefault(),b();const s=r.target.elements[0].value.trim();if(!s){i(),n.warning({message:"Please enter a search term.",position:"topRight"});return}a=1,P(),p();try{const e=await m(s,a,l);if(d=e.totalHits,e.hits.length===0){n.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(e.hits),l*a<d&&L()}catch(e){n.error({message:"Error loading images.",position:"topRight"}),console.error(e)}finally{i()}});const E=async()=>{a+=1,p(),b();try{const r=await m(v,a,l);h(r.hits),l*a<d?L():n.info({message:"We are sorry, but you`ve reached the search results.",position:"topRight"})}catch(r){n.error({message:"Failed to load more images.",position:"topRight"}),console.error(r)}finally{i()}};document.addEventListener("click",r=>{r.target.matches(".load-more-btn")&&E()});
//# sourceMappingURL=index.js.map
